[theme]
primaryColor = "#2a5298"
backgroundColor = "#f0f4f8"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#333333"
font = "sans serif"

[server]
maxUploadSize = 50
enableStaticServing = true

[browser]
gatherUsageStats = false 